package de.evoila.eprofiler.dto.enums;

public enum Industry {
    ARCHITECTURE_AND_PLANNING,
    IT_AND_TELECOMMUNICATION,
    ARTS_ENTERTAINMENT_AND_RECREATION,
    EDUCATIONAL_SERVICES,
    AGRICULTURE_FORESTRY_FISHING_AND_HUNTING

}
